version: "3.8"

services:
  pgdb:
    image: postgres
    container_name: pgdb
    ports:
      - "5432:5432"
    env_file:
      - ./dev/dev.env

  django:
    build:
      context: ./backend
      dockerfile: ../dev/django.dockerfile
    container_name: django
    command: ["python", "manage.py", "test"]
    volumes:
      - ./backend/:/code
    ports:
      - "8000:8000"
    env_file:
      - ./dev/dev.env
    depends_on:
      - pgdb

