version: '3.7'
services:
  web:
    build:
      target: development_build
      context: .
      cache_from:
        - "django-demo:dev"
        - "django-demo:latest"
        - "*"
      args:
        DJANGO_ENV: development
    command: python -Wd manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    restart: unless-stopped
    env_file:
      - ./.env.dev
